import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Layout from '../src/components/Layout/Layout';
import Hero from '../src/sections/Hero/Hero';
import Technologies from '../src/sections/Technologies/Technologies';
import Projects from '../src/sections/Projects/Projects';

export default function Home() {
  return (
    <Layout className={styles.container}>
      <Head>
        <title>Kingba Tech</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero />
      <Technologies />
    </Layout>
  );
}
